name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: tshirts fail
      run: |
        g++ -Wall -Wextra -Werror tshirt.c ut_tshirt.c -o tshirts.out

    - name: misaligned fail
      run: |
        g++ -Wall -Wextra -Werror colorCodeManual.c ut_ColorCodeManual.c -o misaligned.out


    - name: alerter fail
      run: |
        g++ -Wall -Wextra -Werror temperatureAlert.c ut_TemperatureAlert.c -o alerter.out

